name: "random_forest"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "float_input"
    data_type: TYPE_FP32
    dims: [ 4 ]
  }
]
output [
  {
    name: "label"
    data_type: TYPE_INT64
    dims: [ 1 ]
    # O segredo: Damos ao Triton o [1] que ele pede, 
    # mas dizemos para ele "achatar" para [ ] ao falar com o ONNX
    reshape: { shape: [ ] }
  },
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [ 3 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]

dynamic_batching {
  # Quanto tempo (em microsegundos) o Triton deve esperar para tentar
  # formar o batch máximo antes de processar o que já tem na fila.
  max_queue_delay_microseconds: 100 
  
  # Você pode definir tamanhos de batch preferenciais para otimizar o cache da CPU
  preferred_batch_size: [ 4, 8 ]
}